CREATE TABLE [dbo].[GameOdds]
(
    gameId INT NOT NULL,
    bovadaClosingVegasHomeOdds FLOAT NOT NULL DEFAULT 0,
    bovadaClosingVegasAwayOdds FLOAT NOT NULL DEFAULT 0,
    myBookieClosingVegasHomeOdds FLOAT NOT NULL DEFAULT 0,
    myBookieClosingVegasAwayOdds FLOAT NOT NULL DEFAULT 0,
    pinnacleClosingVegasHomeOdds FLOAT NOT NULL DEFAULT 0,
    pinnacleClosingVegasAwayOdds FLOAT NOT NULL DEFAULT 0,
    betOnlineClosingVegasHomeOdds FLOAT NOT NULL DEFAULT 0,
    betOnlineClosingVegasAwayOdds FLOAT NOT NULL DEFAULT 0,
    bet365ClosingVegasHomeOdds FLOAT NOT NULL DEFAULT 0,
    bet365ClosingVegasAwayOdds FLOAT NOT NULL DEFAULT 0,
    bovadaOpeningVegasHomeOdds FLOAT NOT NULL DEFAULT 0,
    bovadaOpeningVegasAwayOdds FLOAT NOT NULL DEFAULT 0,
    myBookieOpeningVegasHomeOdds FLOAT NOT NULL DEFAULT 0,
    myBookieOpeningVegasAwayOdds FLOAT NOT NULL DEFAULT 0,
    pinnacleOpeningVegasHomeOdds FLOAT NOT NULL DEFAULT 0,
    pinnacleOpeningVegasAwayOdds FLOAT NOT NULL DEFAULT 0,
    betOnlineOpeningVegasHomeOdds FLOAT NOT NULL DEFAULT 0,
    betOnlineOpeningVegasAwayOdds FLOAT NOT NULL DEFAULT 0,
    bet365OpeningVegasHomeOdds FLOAT NOT NULL DEFAULT 0,
    bet365OpeningVegasAwayOdds FLOAT NOT NULL DEFAULT 0,
    modelHomeOdds FLOAT NOT NULL DEFAULT 0,
    modelAwayOdds FLOAT NOT NULL DEFAULT 0,
    PRIMARY KEY(gameId),
    FOREIGN KEY (gameId) REFERENCES Game(id),
);